/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_frank_jni_NativeAPI */

#ifndef _Included_com_frank_jni_NativeAPI
#define _Included_com_frank_jni_NativeAPI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_frank_jni_NativeAPI
 * Method:    getJsonFromFile
 * Signature: (Ljava/io/InputStream;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_frank_jni_NativeAPI_getJsonFromFile
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
