/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_frank_ndk_NDKTest */

#ifndef _Included_com_frank_ndk_NDKTest
#define _Included_com_frank_ndk_NDKTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_frank_ndk_NDKTest
 * Method:    square
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_frank_ndk_NDKTest_square
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
